# Site settings
name: From less to more
email: 123@qq.com
author: lhrzy
url: https://github.com/lhuir
resume_site: https://github.com/lhuir
github: https://github.com/lhuir
baseurl: "/lhuir.github.io"
description: Every day keeps accumulating,Constant dripping wears away the stone
meta_description: 紫羽;个人博客;书山有路勤为径，学海无涯苦作舟
motto: The path of the heart is invinciblen.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lhrzy
highlighter: Rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

