# Site settings
name: Less Or More
email: luoyan35714@126.com
author: Freud Kang
url: https://github.com/lhuir
resume_site: https://github.com/lhuir
github: https://github.com/lhuir
baseurl: "/lhuir.github.io"
description: Actually, less is more!
meta_description: 康志华;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714
highlighter: Rouge

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

